PROGRAMS    = ["jar","exe","bin","deb","rpm","msi","appimage","dmg"]
ARCHIVES    = ["zip","7z","tar","bz2","rar","xz","gz","zst"]
AUDIO       = ["mp3","mp2","wav","ogg","aac","flac","alac","dsd","mqa","m4a","opus"]
VIDEO       = ["mp4","mkv","flv","mov","avi","webm", "3gp"]
IMAGE       = ["jpeg","jpg","png","bmp","gif"]
DOCS        = ["pdf","txt","odt","docx","rtf"]
SLIDES      = ["ppt","odp","pptx"]
SPREADSHEET = ["xlsx"]